CREATE TABLE IF NOT EXISTS pa_mst_property (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    parent_id BIGINT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    attributes JSON NULL,
    property_type VARCHAR(80) NOT NULL,
    region VARCHAR(120) NULL,
    address_line1 VARCHAR(255) NULL,
    city VARCHAR(120) NULL,
    emirate VARCHAR(120) NULL,
    country VARCHAR(120) NOT NULL DEFAULT 'UAE',
    ownership_type VARCHAR(80) NULL,
    owner_name VARCHAR(255) NULL,
    title_deed_no VARCHAR(120) NULL,
    rera_permit_no VARCHAR(120) NULL,
    document_reference VARCHAR(255) NULL,
    document_status VARCHAR(80) NULL,
    built_up_area DECIMAL(18,2) NULL,
    plot_area DECIMAL(18,2) NULL,
    market_value DECIMAL(18,2) NULL,
    annual_service_charge DECIMAL(18,2) NULL,
    operating_model VARCHAR(120) NULL,
    facility_manager VARCHAR(255) NULL,
    onboarding_status VARCHAR(80) NOT NULL DEFAULT 'DRAFT',
    active_status ENUM('Y','N') NOT NULL DEFAULT 'Y',
    active_from DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    active_to DATETIME NULL,
    created_by BIGINT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_on DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_pa_mst_property_company_code (company_id, code),
    KEY idx_pa_mst_property_company_status (company_id, active_status, onboarding_status),
    KEY idx_pa_mst_property_region_type (region, property_type)
);

CREATE TABLE IF NOT EXISTS pa_mst_block (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NULL,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    parent_id BIGINT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    attributes JSON NULL,
    active_status ENUM('Y','N') NOT NULL DEFAULT 'Y',
    active_from DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    active_to DATETIME NULL,
    created_by BIGINT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_on DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_pa_mst_block_property_code (parent_id, code),
    KEY idx_pa_mst_block_property_status (parent_id, active_status),
    CONSTRAINT fk_pa_mst_block_property FOREIGN KEY (parent_id) REFERENCES pa_mst_property(id)
);

CREATE TABLE IF NOT EXISTS pa_mst_floor (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NULL,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    parent_id BIGINT NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    attributes JSON NULL,
    active_status ENUM('Y','N') NOT NULL DEFAULT 'Y',
    active_from DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    active_to DATETIME NULL,
    created_by BIGINT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_on DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_pa_mst_floor_block_code (parent_id, code),
    KEY idx_pa_mst_floor_block_status (parent_id, active_status),
    CONSTRAINT fk_pa_mst_floor_block FOREIGN KEY (parent_id) REFERENCES pa_mst_block(id)
);

CREATE TABLE IF NOT EXISTS pa_mst_unit (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NULL,
    property_id BIGINT NOT NULL,
    property_name VARCHAR(255) NOT NULL,
    unit_code VARCHAR(100) NOT NULL,
    unit_type VARCHAR(100) NOT NULL,
    code VARCHAR(100) NULL,
    name VARCHAR(255) NULL,
    description TEXT NULL,
    parent_id BIGINT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    attributes JSON NULL,
    bedrooms INT NULL,
    asking_rent DECIMAL(18,2) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'AVAILABLE',
    active_status ENUM('Y','N') NOT NULL DEFAULT 'Y',
    active_from DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    active_to DATETIME NULL,
    created_by BIGINT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_on DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_pa_mst_unit_code (property_id, unit_code),
    KEY idx_pa_mst_unit_status (status, property_id, unit_type),
    KEY idx_pa_mst_unit_floor_status (parent_id, active_status, sort_order),
    CONSTRAINT fk_pa_mst_unit_floor FOREIGN KEY (parent_id) REFERENCES pa_mst_floor(id)
);

CREATE TABLE IF NOT EXISTS pa_mst_amenity (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NULL,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    parent_id BIGINT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    attributes JSON NULL,
    active_status ENUM('Y','N') NOT NULL DEFAULT 'Y',
    active_from DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    active_to DATETIME NULL,
    created_by BIGINT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_on DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_pa_mst_amenity_parent_code (parent_id, code),
    KEY idx_pa_mst_amenity_parent_status (parent_id, active_status)
);

CREATE TABLE IF NOT EXISTS pa_mst_property_ownership (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    property_id BIGINT NOT NULL,
    party VARCHAR(255) NOT NULL,
    role VARCHAR(160) NOT NULL,
    share_right VARCHAR(160) NULL,
    reference VARCHAR(255) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    sort_order INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_on DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_pa_mst_property_ownership_property (property_id, status, sort_order),
    CONSTRAINT fk_pa_mst_property_ownership_property FOREIGN KEY (property_id) REFERENCES pa_mst_property(id)
);

CREATE TABLE IF NOT EXISTS pa_mst_property_document (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    property_id BIGINT NOT NULL,
    document VARCHAR(255) NOT NULL,
    category VARCHAR(120) NOT NULL,
    reference VARCHAR(255) NOT NULL,
    updated_date VARCHAR(40) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    sort_order INT NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_on DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_pa_mst_property_document_property (property_id, status, sort_order),
    CONSTRAINT fk_pa_mst_property_document_property FOREIGN KEY (property_id) REFERENCES pa_mst_property(id)
);

CREATE TABLE IF NOT EXISTS pa_txn_property_workflow (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    property_id BIGINT NOT NULL,
    step_code VARCHAR(80) NOT NULL,
    step_name VARCHAR(160) NOT NULL,
    owner_name VARCHAR(255) NULL,
    progress_percent INT NOT NULL DEFAULT 0,
    state VARCHAR(80) NOT NULL DEFAULT 'PENDING',
    sort_order INT NOT NULL DEFAULT 0,
    updated_by BIGINT NULL,
    updated_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_pa_txn_property_workflow_step (property_id, step_code),
    KEY idx_pa_txn_property_workflow_property (property_id, sort_order),
    CONSTRAINT fk_pa_txn_property_workflow_property FOREIGN KEY (property_id) REFERENCES pa_mst_property(id)
);

CREATE TABLE IF NOT EXISTS pa_txn_leasing_lead (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    lead_no VARCHAR(50) NOT NULL,
    customer_id BIGINT NULL,
    customer_code VARCHAR(50) NULL,
    customer_type INT NULL,
    customer_name VARCHAR(255) NOT NULL,
    contact_person VARCHAR(255) NULL,
    mobile_no VARCHAR(60) NOT NULL,
    email VARCHAR(255) NULL,
    preferred_contact_method VARCHAR(40) NULL,
    purpose VARCHAR(40) NOT NULL DEFAULT 'RENT',
    status VARCHAR(50) NOT NULL DEFAULT 'NEW',
    qualification_score INT NULL,
    qualification_notes TEXT NULL,
    created_by BIGINT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_on DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_pa_txn_leasing_lead_no (lead_no),
    KEY idx_pa_txn_leasing_lead_company (company_id),
    KEY idx_pa_txn_leasing_lead_status (status, created_on),
    KEY idx_pa_txn_leasing_lead_mobile (mobile_no),
    KEY idx_pa_txn_leasing_lead_customer_code (company_id, customer_code)
);

CREATE TABLE IF NOT EXISTS pa_txn_leasing_prospect (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    lead_id BIGINT NULL,
    prospect_no VARCHAR(50) NOT NULL,
    customer_id BIGINT NULL,
    customer_code VARCHAR(50) NULL,
    customer_type INT NULL,
    customer_name VARCHAR(255) NOT NULL,
    trade_license_no VARCHAR(100) NULL,
    cr_number VARCHAR(100) NULL,
    vat_registration_no VARCHAR(100) NULL,
    contact_person VARCHAR(255) NULL,
    contact_role VARCHAR(80) NULL,
    contact_title VARCHAR(120) NULL,
    mobile_no VARCHAR(60) NOT NULL,
    phone_no VARCHAR(60) NULL,
    email VARCHAR(255) NULL,
    preferred_contact_method VARCHAR(40) NULL,
    fax_no VARCHAR(60) NULL,
    address VARCHAR(500) NULL,
    source VARCHAR(100) NULL,
    purpose VARCHAR(40) NULL,
    commercial_need VARCHAR(255) NULL,
    document_notes TEXT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PROSPECT',
    created_by BIGINT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_on DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_pa_txn_leasing_prospect_no (prospect_no),
    UNIQUE KEY uq_pa_txn_leasing_prospect_lead (lead_id),
    KEY idx_pa_txn_leasing_prospect_company (company_id),
    CONSTRAINT fk_pa_txn_leasing_prospect_lead FOREIGN KEY (lead_id) REFERENCES pa_txn_leasing_lead(id)
);

CREATE TABLE IF NOT EXISTS pa_txn_leasing_requirement (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    prospect_id BIGINT NOT NULL,
    property_id BIGINT NULL,
    property_name VARCHAR(255) NULL,
    requirement_level VARCHAR(40) NULL,
    block_name VARCHAR(120) NULL,
    floor_name VARCHAR(120) NULL,
    preferred_unit_id BIGINT NULL,
    unit_type VARCHAR(100) NULL,
    bedrooms INT NULL,
    area_from DECIMAL(18,2) NULL,
    area_to DECIMAL(18,2) NULL,
    budget_from DECIMAL(18,2) NULL,
    budget_to DECIMAL(18,2) NULL,
    move_in_date DATE NULL,
    lease_term_months INT NULL,
    usage_type VARCHAR(120) NULL,
    parking_required TINYINT(1) NULL,
    fit_out_required TINYINT(1) NULL,
    special_requirements TEXT NULL,
    notes TEXT NULL,
    created_by BIGINT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_on DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_pa_txn_leasing_req_company (company_id),
    KEY idx_pa_txn_leasing_req_prospect (prospect_id),
    KEY idx_pa_txn_leasing_req_unit (preferred_unit_id),
    CONSTRAINT fk_pa_txn_leasing_req_prospect FOREIGN KEY (prospect_id) REFERENCES pa_txn_leasing_prospect(id),
    CONSTRAINT fk_pa_txn_leasing_req_unit FOREIGN KEY (preferred_unit_id) REFERENCES pa_mst_unit(id)
);

CREATE TABLE IF NOT EXISTS pa_txn_leasing_site_visit (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    prospect_id BIGINT NOT NULL,
    property_id BIGINT NULL,
    property_name VARCHAR(255) NULL,
    requirement_level VARCHAR(40) NULL,
    block_name VARCHAR(120) NULL,
    floor_name VARCHAR(120) NULL,
    unit_id BIGINT NULL,
    visit_at DATETIME NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'SCHEDULED',
    notes TEXT NULL,
    created_by BIGINT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_on DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_pa_txn_leasing_visit_company (company_id),
    KEY idx_pa_txn_leasing_visit_prospect (prospect_id, visit_at),
    KEY idx_pa_txn_leasing_visit_unit (unit_id, visit_at),
    CONSTRAINT fk_pa_txn_leasing_visit_prospect FOREIGN KEY (prospect_id) REFERENCES pa_txn_leasing_prospect(id),
    CONSTRAINT fk_pa_txn_leasing_visit_unit FOREIGN KEY (unit_id) REFERENCES pa_mst_unit(id)
);

CREATE TABLE IF NOT EXISTS pa_txn_leasing_offer (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    prospect_id BIGINT NOT NULL,
    property_id BIGINT NULL,
    property_name VARCHAR(255) NULL,
    requirement_level VARCHAR(40) NULL,
    block_name VARCHAR(120) NULL,
    floor_name VARCHAR(120) NULL,
    unit_id BIGINT NULL,
    offer_no VARCHAR(50) NOT NULL,
    base_amount DECIMAL(18,2) NOT NULL,
    discount_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    final_amount DECIMAL(18,2) NOT NULL,
    special_terms TEXT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
    approval_required TINYINT(1) NOT NULL DEFAULT 0,
    created_by BIGINT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_on DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_pa_txn_leasing_offer_no (offer_no),
    KEY idx_pa_txn_leasing_offer_company (company_id),
    KEY idx_pa_txn_leasing_offer_prospect (prospect_id, status),
    KEY idx_pa_txn_leasing_offer_unit (unit_id, status),
    CONSTRAINT fk_pa_txn_leasing_offer_prospect FOREIGN KEY (prospect_id) REFERENCES pa_txn_leasing_prospect(id),
    CONSTRAINT fk_pa_txn_leasing_offer_unit FOREIGN KEY (unit_id) REFERENCES pa_mst_unit(id)
);

CREATE TABLE IF NOT EXISTS pa_txn_leasing_negotiation (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    offer_id BIGINT NOT NULL,
    proposed_amount DECIMAL(18,2) NOT NULL,
    notes TEXT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'OPEN',
    created_by BIGINT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_pa_txn_leasing_neg_company (company_id),
    KEY idx_pa_txn_leasing_neg_offer (offer_id, created_on),
    CONSTRAINT fk_pa_txn_leasing_neg_offer FOREIGN KEY (offer_id) REFERENCES pa_txn_leasing_offer(id)
);

CREATE TABLE IF NOT EXISTS pa_txn_leasing_reservation (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    reservation_no VARCHAR(50) NOT NULL,
    lead_id BIGINT NULL,
    prospect_id BIGINT NOT NULL,
    offer_id BIGINT NOT NULL,
    property_id BIGINT NOT NULL,
    unit_id BIGINT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
    approval_status VARCHAR(50) NOT NULL DEFAULT 'NOT_REQUIRED',
    reservation_fee DECIMAL(18,2) NOT NULL DEFAULT 0,
    paid_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
    payment_waived TINYINT(1) NOT NULL DEFAULT 0,
    expires_at DATETIME NULL,
    created_by BIGINT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_on DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_pa_txn_leasing_reservation_no (reservation_no),
    KEY idx_pa_txn_leasing_res_company (company_id),
    KEY idx_pa_txn_leasing_res_unit_status (unit_id, status),
    KEY idx_pa_txn_leasing_res_prospect (prospect_id, status),
    KEY idx_pa_txn_leasing_res_offer (offer_id),
    CONSTRAINT fk_pa_txn_leasing_res_lead FOREIGN KEY (lead_id) REFERENCES pa_txn_leasing_lead(id),
    CONSTRAINT fk_pa_txn_leasing_res_prospect FOREIGN KEY (prospect_id) REFERENCES pa_txn_leasing_prospect(id),
    CONSTRAINT fk_pa_txn_leasing_res_offer FOREIGN KEY (offer_id) REFERENCES pa_txn_leasing_offer(id),
    CONSTRAINT fk_pa_txn_leasing_res_unit FOREIGN KEY (unit_id) REFERENCES pa_mst_unit(id)
);

CREATE TABLE IF NOT EXISTS pa_txn_leasing_payment_receipt (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    reservation_id BIGINT NOT NULL,
    receipt_no VARCHAR(50) NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    paid_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    erp_receipt_id BIGINT NULL,
    created_by BIGINT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_pa_txn_leasing_receipt_no (receipt_no),
    KEY idx_pa_txn_leasing_receipt_res (reservation_id),
    CONSTRAINT fk_pa_txn_leasing_receipt_res FOREIGN KEY (reservation_id) REFERENCES pa_txn_leasing_reservation(id)
);

CREATE TABLE IF NOT EXISTS pa_txn_leasing_status_history (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    entity_type VARCHAR(80) NOT NULL,
    entity_id BIGINT NOT NULL,
    from_status VARCHAR(80) NULL,
    to_status VARCHAR(80) NOT NULL,
    comments TEXT NULL,
    changed_by BIGINT NULL,
    changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_pa_txn_leasing_hist_entity (entity_type, entity_id, changed_at)
);

CREATE TABLE IF NOT EXISTS pa_txn_legal_card (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    legal_card_no VARCHAR(40) NOT NULL,
    legal_type_id BIGINT NOT NULL,
    current_stage_id BIGINT NOT NULL,
    reason_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    property_id BIGINT NOT NULL,
    unit_id BIGINT NOT NULL,
    advocate_id BIGINT NULL,
    case_number VARCHAR(80) NULL,
    priority ENUM('H', 'M', 'L') NOT NULL DEFAULT 'M',
    document_status_id BIGINT NOT NULL,
    approval_status_id BIGINT NOT NULL,
    document_date DATE NOT NULL,
    due_date DATE NOT NULL,
    due_amount DECIMAL(14,2) NOT NULL,
    created_by BIGINT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_on DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_pa_txn_legal_card_no (legal_card_no),
    KEY idx_pa_txn_legal_card_company (company_id),
    KEY idx_pa_txn_legal_card_doc_date (document_date),
    KEY idx_pa_txn_legal_card_status (document_status_id, approval_status_id),
    KEY idx_pa_txn_legal_card_type (legal_type_id),
    KEY idx_pa_txn_legal_card_property_unit (property_id, unit_id)
);

CREATE TABLE IF NOT EXISTS pa_txn_legal_card_attachment (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    legal_card_id BIGINT NOT NULL,
    document_type_id BIGINT NOT NULL,
    document_name VARCHAR(255) NULL,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(120) NULL,
    content_data LONGTEXT NULL,
    storage_path VARCHAR(500) NULL,
    created_by BIGINT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_on DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_pa_txn_legal_card_att_card (legal_card_id),
    KEY idx_pa_txn_legal_card_att_company (company_id, legal_card_id),
    CONSTRAINT fk_pa_txn_legal_card_att_card FOREIGN KEY (legal_card_id) REFERENCES pa_txn_legal_card(id)
);

CREATE TABLE IF NOT EXISTS pa_txn_legal_card_timeline (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    company_id BIGINT NOT NULL,
    legal_card_id BIGINT NOT NULL,
    status_id BIGINT NOT NULL,
    step VARCHAR(120) NOT NULL,
    `action` VARCHAR(60) NOT NULL,
    remarks VARCHAR(1000) NULL,
    created_by BIGINT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT NULL,
    updated_on DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_pa_txn_legal_card_timeline_card (legal_card_id, created_on),
    KEY idx_pa_txn_legal_card_timeline_company (company_id, legal_card_id, created_on),
    CONSTRAINT fk_pa_txn_legal_card_timeline_card FOREIGN KEY (legal_card_id) REFERENCES pa_txn_legal_card(id)
);
