UPDATE pa_txn_leasing_prospect
SET status = CASE
    WHEN status IN ('ACTIVE', 'NEW', 'QUALIFIED', 'PROSPECT', 'PROSPECT_CREATED') THEN 'PROSPECT'
    WHEN status IN ('REQUIREMENT', 'REQUIREMENT_CAPTURED', 'REQUIREMENT_UPDATED') THEN 'REQUIREMENT_CAPTURED'
    WHEN status IN ('VISIT', 'SITE_VISIT', 'SITE_VISIT_SCHEDULED', 'SITE_VISIT_COMPLETED') THEN 'SITE_VISIT_SCHEDULED'
    WHEN status IN ('OFFER', 'OFFER_DRAFT', 'OFFER_PENDING_APPROVAL', 'OFFER_APPROVED', 'OFFER_SENT', 'OFFERED', 'OFFER_IN_PROGRESS') THEN 'OFFER_IN_PROGRESS'
    WHEN status IN ('NEGOTIATION', 'NEGOTIATION_IN_PROGRESS') THEN 'NEGOTIATION_IN_PROGRESS'
    WHEN status IN ('RESERVATION', 'RESERVED', 'LEASE_PROCESS', 'RESERVATION_REQUESTED', 'RESERVATION_PENDING_APPROVAL', 'PAYMENT_PENDING', 'MOVED_TO_LEASE') THEN 'RESERVATION_IN_PROGRESS'
    ELSE status
END
WHERE status IN (
    'ACTIVE', 'NEW', 'QUALIFIED', 'PROSPECT', 'PROSPECT_CREATED',
    'REQUIREMENT', 'REQUIREMENT_CAPTURED', 'REQUIREMENT_UPDATED',
    'VISIT', 'SITE_VISIT', 'SITE_VISIT_SCHEDULED', 'SITE_VISIT_COMPLETED',
    'OFFER', 'OFFER_DRAFT', 'OFFER_PENDING_APPROVAL', 'OFFER_APPROVED', 'OFFER_SENT', 'OFFERED', 'OFFER_IN_PROGRESS',
    'NEGOTIATION', 'NEGOTIATION_IN_PROGRESS',
    'RESERVATION', 'RESERVED', 'LEASE_PROCESS', 'RESERVATION_REQUESTED', 'RESERVATION_PENDING_APPROVAL', 'PAYMENT_PENDING', 'MOVED_TO_LEASE'
);

ALTER TABLE pa_txn_leasing_prospect
    ALTER COLUMN status SET DEFAULT 'PROSPECT';
