package com.eba.propertyconnect.propertymanagement.leasing.domain;

public final class LeasingStatuses {

	private LeasingStatuses() {
	}

	public enum LeadStatus {
		NEW,
		OPEN,
		QUALIFIED,
		UNIT_SHORTLISTED,
		SITE_VISIT_SCHEDULED,
		SITE_VISIT_COMPLETED,
		OFFER_DRAFT,
		OFFER_PENDING_APPROVAL,
		OFFER_APPROVED,
		OFFER_SENT,
		PROPOSAL_CREATED,
		NEGOTIATION,
		OFFER_ACCEPTED,
		RESERVATION_REQUESTED,
		RESERVATION_PENDING_APPROVAL,
		PAYMENT_PENDING,
		RESERVED,
		MOVED_TO_LEASE,
		WON,
		CONVERTED_TO_PROSPECT,
		LOST,
		ON_HOLD,
		DUPLICATE,
		CANCELLED,
		EXPIRED
	}

	public enum ProspectStatus {
		PROSPECT,
		REQUIREMENT_CAPTURED,
		SITE_VISIT_SCHEDULED,
		OFFER_IN_PROGRESS,
		NEGOTIATION_IN_PROGRESS,
		RESERVATION_IN_PROGRESS
	}

	public enum UnitStatus {
		AVAILABLE,
		SHORTLISTED,
		ON_HOLD,
		RESERVED,
		LEASED,
		BLOCKED,
		MAINTENANCE
	}

	public enum VisitStatus {
		SCHEDULED,
		COMPLETED,
		CANCELLED
	}

	public enum OfferStatus {
		DRAFT,
		PENDING_APPROVAL,
		RETURNED,
		APPROVED,
		REJECTED,
		SENT,
		NEGOTIATION,
		ACCEPTED,
		LOST,
		CANCELLED
	}

	public enum ReservationStatus {
		DRAFT,
		PENDING_APPROVAL,
		REJECTED,
		PAYMENT_PENDING,
		PAID,
		CONFIRMED,
		CANCELLED,
		EXPIRED,
		MOVED_TO_LEASE
	}

	public enum ApprovalStatus {
		NOT_REQUIRED,
		PENDING,
		APPROVED,
		REJECTED
	}
}
